services:
  - type: web
    name: compa94
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
